"""Utils package for convert_to_quant."""
from .tensor_utils import (
    dict_to_tensor,
    tensor_to_dict,
    normalize_tensorwise_scales,
    generate_calibration_data,
    adaptive_lr_update,
    compute_bias_correction,
)
from .comfy_quant import (
    create_comfy_quant_tensor,
    fix_comfy_quant_params_structure,
    parse_add_keys_string,
    edit_comfy_quant,
    should_skip_layer_for_performance,
)
from .logging import (
    setup_logging,
    info,
    verbose,
    debug,
    minimal,
    warning,
    error,
    log_debug,
)
from .hadamard import (
    is_power_of_two,
    hadamard_matrix,
    fast_hadamard_transform,
    random_orthogonal_matrix,
    fast_hadamard_transform_chunked,
    fast_hadamard_transform_2d_chunked,
    fast_hadamard_transform_2d_chunked_with_signs,
)
from .memory_utils import (
    OOMGuard,
    MemorySummary,
    should_use_cpu_for_hadamard,
    should_use_cpu_for_ldlq,
    should_use_cpu_for_hessian,
    format_bytes,
    set_no_memory_limits,
    get_no_memory_limits,
    memory_limits_disabled,
    maybe_empty_cache,
    synchronize_and_empty_cache,
)
from .pinned_pool import (
    PinnedMemoryPool,
    get_pinned_pool,
    transfer_with_pool,
    clear_pinned_pool,
    get_pinned_pool_stats,
)
from .buffer_pool import (
    LDLQBufferPool,
    get_buffer_pool,
    clear_buffer_pool,
    get_buffer_pool_stats,
)
from .checkpointed_quant import (
    checkpointed_ldlq,
    CheckpointedQuantizer,
    estimate_checkpointed_memory,
)
from .async_prefetch import (
    AsyncLayerLoader,
    BatchedAsyncLoader,
    PrefetchStats,
    create_async_loader,
)
from .tensor_prefetch import (
    AsyncTensorPrefetcher,
    TensorPrefetchStats,
)

__all__ = [
    "dict_to_tensor",
    "tensor_to_dict",
    "normalize_tensorwise_scales",
    "generate_calibration_data",
    "adaptive_lr_update",
    "compute_bias_correction",
    "create_comfy_quant_tensor",
    "fix_comfy_quant_params_structure",
    "parse_add_keys_string",
    "edit_comfy_quant",
    "should_skip_layer_for_performance",
    "setup_logging",
    "info",
    "verbose",
    "debug",
    "minimal",
    "warning",
    "error",
    "log_debug",
    "is_power_of_two",
    "hadamard_matrix",
    "fast_hadamard_transform",
    "random_orthogonal_matrix",
    "fast_hadamard_transform_chunked",
    "fast_hadamard_transform_2d_chunked",
    "fast_hadamard_transform_2d_chunked_with_signs",
    "OOMGuard",
    "MemorySummary",
    "should_use_cpu_for_hadamard",
    "should_use_cpu_for_ldlq",
    "should_use_cpu_for_hessian",
    "format_bytes",
    "set_no_memory_limits",
    "get_no_memory_limits",
    "memory_limits_disabled",
    "maybe_empty_cache",
    "synchronize_and_empty_cache",
    "PinnedMemoryPool",
    "get_pinned_pool",
    "transfer_with_pool",
    "clear_pinned_pool",
    "get_pinned_pool_stats",
    "LDLQBufferPool",
    "get_buffer_pool",
    "clear_buffer_pool",
    "get_buffer_pool_stats",
    "checkpointed_ldlq",
    "CheckpointedQuantizer",
    "estimate_checkpointed_memory",
    "AsyncLayerLoader",
    "BatchedAsyncLoader",
    "PrefetchStats",
    "create_async_loader",
    "AsyncTensorPrefetcher",
    "TensorPrefetchStats",
]
